### PR TITLE
Fix - complement mask in denomiantor loglikelihood

### PR DESCRIPTION
**Pull request by andreabac3**
Subtraction, the `-` operator, with a bool tensor is not supported. If you are trying to invert a mask, use the `~` or `logical_not()` operator instead.

### CODE REVIEW

**Comment by rikeda71** [comment]
@andreabac3 
Thank you for your contribution.
I ran the tests in this rep (test code in `tests/`) after your contribution, I encountered the following errors.

```
======================================================================
ERROR: test_compute_log_likelihood (tests.test_crf.TestCRF)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/rikeda/Development/TorchCRF/tests/test_crf.py", line 55, in test_compute_log_likelihood
    self.hidden, self.mask)
  File "/Users/rikeda/Development/TorchCRF/TorchCRF/__init__.py", line 183, in _compute_denominator_log_likelihood
    score = score_t * mask_t + score * (~ mask_t)
TypeError: ~ (operator.invert) is only implemented on integer and Boolean-type tensors

======================================================================
ERROR: test_forward (tests.test_crf.TestCRF)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/rikeda/Development/TorchCRF/tests/test_crf.py", line 48, in test_forward
    fvalue = self.crf.forward(self.hidden, self.labels, self.mask)
  File "/Users/rikeda/Development/TorchCRF/TorchCRF/__init__.py", line 54, in forward
    log_denominator = self._compute_denominator_log_likelihood(h, mask)
  File "/Users/rikeda/Development/TorchCRF/TorchCRF/__init__.py", line 183, in _compute_denominator_log_likelihood
    score = score_t * mask_t + score * (~ mask_t)
TypeError: ~ (operator.invert) is only implemented on integer and Boolean-type tensors

----------------------------------------------------------------------
```

So, I patched as below to fix errors.
Could you please confirm my patches.

Thanks.

**Review by andreabac3 — COMMENTED** [review]
Now you can merge it :) 
I have fixed a device error as you can see in my last commit.

**Comment by rikeda71** [comment]
@andreabac3 
Thanks for your fixing.

**Comment by andreabac3** [comment]
You are welcome :)
I want to make further pull requests in the future.

**Pull request merged**
